### ISSUE TITLE
Can't use Light_Analysis_Examples/ Python/Thorlabs PMxxx Power Meters/PMxxx using ctypes - Python 3.py to connect PM103E

### ISSUE THREAD

**Issue by leominami777** [Thorlabs/Light_Analysis_Examples#15]
I use Light_Analysis_Examples/ Python/Thorlabs PMxxx Power Meters/PMxxx using ctypes - Python 3.py to connet my PM103E,have  the erro NameError: b'Insufficient location information or the device or resource is not present in the system.'
I alse use pyvisa  "visa.ResourceManager().list_resources()" and NI-Max  to search the Device port,but find no thing.
But i can use the "Thorlabs Optical Power Monitor.exe" to connect the PM103E.
How can i to find the  Device port without "Thorlabs Optical Power Monitor.exe"

**Comment by gboedecker** [comment]
Hi leominami777, make sure that you close the Optical Power Monitor software before you start the example. If that was not the reason, please contact techsupport@thorlabs.com.
